name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci --legacy-peer-deps

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Start Cloud SQL Auth Proxy
        run: |
          curl -o cloud_sql_proxy https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64
          chmod +x cloud_sql_proxy
          ./cloud_sql_proxy -instances=${{ secrets.GCP_PROJECT }}:us-central1:aspire-map-db=tcp:5432 &
          sleep 5 # wait for proxy to start

      - name: Prisma migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-docker.pkg.dev

      - name: Build & Push Docker Image
        run: |
          docker build -t us-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/backend-repo/backend:${{ github.sha }} .
          docker push us-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/backend-repo/backend:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy backend-service \
            --image=us-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/backend-repo/backend:${{ github.sha }} \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated \
            --set-secrets=DATABASE_URL=DATABASE_URL:latest,PINECONE_API_KEY=PINECONE_API_KEY:latest,GEMINI_API_KEY=GEMINI_API_KEY:latest
