name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE_NAME: backend-service
  REGION: us-central1
  REPOSITORY: backend-repo

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Download and setup Cloud SQL Auth Proxy
        run: |
          wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
          chmod +x cloud_sql_proxy

      - name: Start Cloud SQL Auth Proxy
        run: |
          ./cloud_sql_proxy -instances=${{ secrets.DB_INSTANCE_CONNECTION_NAME }}=tcp:5432 \
            -log_debug_stdout &
          PROXY_PID=$!
          echo "PROXY_PID=$PROXY_PID" >> $GITHUB_ENV

          # Wait for proxy to be ready
          echo "Waiting for Cloud SQL Auth Proxy to start..."
          for i in {1..30}; do
            if nc -z localhost 5432; then
              echo "✅ Cloud SQL Proxy is ready on localhost:5432"
              break
            elif [ $i -eq 30 ]; then
              echo "❌ Cloud SQL Proxy failed to start within 60 seconds"
              exit 1
            fi
            echo "Waiting for Cloud SQL Proxy... ($i/30)"
            sleep 2
          done

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Prisma migrations
        env:
          DATABASE_URL: 'postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@localhost:5432/${{ secrets.DB_NAME }}?sslmode=disable'
        run: |
          echo "Running Prisma migrations..."
          echo "Testing database connection..."

          # Test connection first
          if npx prisma db execute --stdin <<< "SELECT 1;" 2>/dev/null; then
            echo "✅ Database connection successful"
          else
            echo "❌ Database connection failed"
            echo "Checking if proxy is still running..."
            ps aux | grep cloud_sql_proxy || true
            exit 1
          fi

          # Run migrations
          echo "Deploying migrations..."
          npx prisma migrate deploy --schema=./prisma/schema.prisma
          echo "✅ Migrations completed successfully"

      - name: Stop Cloud SQL Auth Proxy
        run: pkill -f cloud_sql_proxy || true

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-docker.pkg.dev

      - name: Build Docker Image
        run: |
          docker build -t us-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push us-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image=us-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --platform=managed \
            --region=${{ env.REGION }} \
            --allow-unauthenticated \
            --port=3000 \
            --memory=512Mi \
            --cpu=1 \
            --min-instances=0 \
            --max-instances=10 \
            --set-env-vars="NODE_ENV=production" \
            --set-secrets="DATABASE_URL=DATABASE_URL:latest,PINECONE_API_KEY=PINECONE_API_KEY:latest,GEMINI_API_KEY=GEMINI_API_KEY:latest"
